import os

NUM_ENADE_EXAM_QUESTIONS = 40
MAX_SUBJECTS_BY_QUESTION = 3
CODE_BLANK_DIS_ANSWER = 333
CODE_BLANK_OBJ_ANSWER = "."
CODE_DELETION_OBJ_ANSWER = "*"  # rasura
CODE_CANCELLED_DIS_QUESTION = 335
CODE_CANCELLED_OBJ_QUESTION = ["X", "Z", "N"]
BLANK_LABEL = "BRANCO"
CANCELLED_LABEL = "NULA"
DELETION_LABEL = "RASURA"
CODE_COURSE = 13881  # 12025
STUDENT_CODE_PRESENT = 555
PRESENCE_COLUMN = "TP_PRES"
DATA_DIR = "data"
SUBJECT_DF_NAME = "classificacao_charao.csv"
SUBJECT_DF_PATH = os.path.join(DATA_DIR, SUBJECT_DF_NAME)
